Add monokai
jgillich/faststack pull request #23
Opened 2016-12-16 13:17 UTC by abhineet97

Based on a [TextMate color theme](http://www.monokai.nl/blog/2006/07/15/textmate-color-theme/) which I think is the [origin](http://www.monokai.nl/blog/2006/07/15/textmate-color-theme/) of this theme.

2016-12-16 15:29 UTC, jgillich requested changes

2016-12-16 15:29 UTC, jgillich commented on app/themes.js
> +      'color-palette-overrides': solarizedOverrides,
Can you also change the color palette? I've found [this one](https://gist.github.com/maxfragg/6234908), but they also use slightly different bg/fg colors, not sure if there are sources that match the original Textmate theme.

2016-12-17 12:29 UTC, abhineet97 commented
I added all the colors that I could find in monokai [TextMate theme file](http://www.monokai.nl/blog/wp-content/asdev/Monokai.tmTheme).
I hope this is what you requested.

2016-12-17 19:01 UTC, jgillich commented
Not quite, the palette consists of 16 colors, [here's](http://chriskempson.com/projects/base16/) a list of how they're meant to be used. Usually you should be able to just copy and paste them from another terminal theme file.

I've added monokai in f295c49aba2b310647462432dcffb225a2a80927, thank you for the effort!

2016-12-17 19:01 UTC, closed without merging